name: iOS Release

on:
  push:
    branches: [ "main","develop"]
  pull_request:
    branches: [ "main","develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  APP_NAME: QtApp
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.9.0
  ARTIFACT:     qtapp_ios_release.zip

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python with virtual environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Use a specific, common Python 3 version

    - name: Install aqtinstall and its dependencies into the virtual environment
      # The virtual environment should be active from the previous step.
      # `pip` will now install into the venv.
      run: |
        python -m pip install --upgrade pip
        python -m pip install aqtinstall

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }} 
        host: 'mac'
        target: 'ios'
        arch: 'ios'
        setup-python: false
    
    - name: Create Build Directory
      run: mkdir build

    - name: \[DEBUG] Which CMake and which env vars?
      shell: bash
      working-directory: build
      run: |
        which cmake
        cmake --version
        env

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: |
        chmod +x ./configure.sh
        ./configure.sh
                  
    - name: Build Application
      working-directory: build
      run: xcodebuild build -allowProvisioningUpdates -project QtApp.xcodeproj -scheme QtApp -configuration Debug -destination "generic/platform=iOS" -destination-timeout 1 ENABLE_ONLY_ACTIVE_RESOURCES=NO

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-bundle
        # The .app bundle is typically found in build/<Configuration>-iphoneos/<AppName>.app when using the Xcode generator
        path: build/Debug-iphoneos/${{ env.APP_NAME }}.app 