name: Linux Release

on:
  push:
    branches: [ "main","develop"]
  pull_request:
    branches: [ "main","develop" ]
  workflow_dispatch:

jobs:
  build:
    #if: false    
    
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@v4.0.2

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.1'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        use-official: false
        modules: 'qtquick3d'

    - name: Configure CMake
      run: |
        mkdir build
        cmake -S . -B build \
          -DCMAKE_PREFIX_PATH=./Qt/6.9.1/gcc_64/lib/cmake

    - name: Build project
      run: cmake --build build --config Release

  build_flatpak_arm64:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@v4.0.2

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.1'
        host: 'linux_arm64'
        target: 'desktop'
        arch: 'linux_gcc_arm64'
        use-official: false
        modules: 'qtquick3d'

    - name: Install Flatpak and Flatpak Builder (Manual)
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder

    - name: Set up Flatpak remotes
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak remote-add --if-not-exists kdeapps https://sdk.kde.org/kdeapps.flatpakrepo

    - name: Flatpak build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
          bundle: qtapp.flatpak
          manifest-path: configure_build_deploy_linux.yml
          cache-key: flatpak-builder-${{ github.sha }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: qtapp-flatpak-bundle
          path: qtapp.flatpak
