name: macOS Release

on:
  push:
    branches: [ "main","develop"]
  pull_request:
    branches: [ "main","develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: false

    runs-on: macos-15

    env:
      # Default build dir. Will be overwritten by the configure build scripts.
      BUILD_DIR: "build"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure and build for MacOS target
      shell: bash
      run: |
        chmod +x ./configure_build_macos.sh
        ./configure_build_macos.sh
  
    - name: Upload MacOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: qtapp-macos
        # Build dir was given by the configure script
        path: ${{ env.BUILD_DIR }}/*.dmg

    - name: Configure and build for iOS simulator target
      shell: bash
      run: |
        chmod +x ./configure_build_ios_simulator.sh
        ./configure_build_ios_simulator.sh

    - name: Upload iOS simulator Artifact
      uses: actions/upload-artifact@v4
      with:
        name: qtapp-ios-simulator
        # Build dir was given by the configure script
        path: ${{ env.BUILD_DIR }}/Release-iphonesimulator/*

    - name: Configure and build for iOS target
      shell: bash
      run: |
        chmod +x ./configure_build_ios.sh
        ./configure_build_ios.sh

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: qtapp-ios
        # Build dir was given by the configure script
        path: ${{ env.BUILD_DIR }}/Release-iphoneos/*